import { 
  SaudiCity, 
  OccasionType, 
  ServiceCategory, 
  Vendor, 
  ServiceItem, 
  SmartPackage, 
  Occasion, 
  Guest, 
  SeatingTable, 
  BudgetItem, 
  PlanningTask, 
  WishlistGift, 
  InspirationPost, 
  RFQRequest, 
  Booking, 
  Review, 
  AdminPlatformConfig,
  RunOfShowItem
} from './types';

export const SAUDI_CITIES: SaudiCity[] = [
  {
    id: 'riyadh',
    nameAr: 'الرياض',
    nameEn: 'Riyadh',
    regionAr: 'منطقة الرياض',
    neighborhoods: ['الملقا', 'النرجس', 'الياسمين', 'حطين', 'العليا', 'الصحافة', 'السليمانية', 'الرمال', 'العارض', 'الدرعية'],
    isAvailable: true,
  },
  {
    id: 'jeddah',
    nameAr: 'جدة',
    nameEn: 'Jeddah',
    regionAr: 'منطقة مكة المكرمة',
    neighborhoods: ['الشاطئ', 'الروضة', 'الحمراء', 'أبحر الشمالية', 'المرجان', 'البساتين', 'الصفا', 'الفيصلية'],
    isAvailable: true,
  },
  {
    id: 'makkah',
    nameAr: 'مكة المكرمة',
    nameEn: 'Makkah',
    regionAr: 'منطقة مكة المكرمة',
    neighborhoods: ['العزيزية', 'بطحاء قريش', 'العوالي', 'الشوقية', 'النزهة'],
    isAvailable: true,
  },
  {
    id: 'madinah',
    nameAr: 'المدينة المنورة',
    nameEn: 'Madinah',
    regionAr: 'منطقة المدينة المنورة',
    neighborhoods: ['العزيزية', 'سلطانة', 'الهجرة', 'القبلتين', 'الأزهري'],
    isAvailable: true,
  },
  {
    id: 'dammam',
    nameAr: 'الدمام',
    nameEn: 'Dammam',
    regionAr: 'المنطقة الشرقية',
    neighborhoods: ['الشاطئ الغربي', 'المزروعية', 'الفيصلية', 'طيبة', 'الشعلة'],
    isAvailable: true,
  },
  {
    id: 'khobar',
    nameAr: 'الخبر',
    nameEn: 'Al Khobar',
    regionAr: 'المنطقة الشرقية',
    neighborhoods: ['الحزام الأخضر', 'الحزام الذهبي', 'الراكة الجنوبية', 'العزيزية', 'الكورنيش'],
    isAvailable: true,
  },
  {
    id: 'ahsa',
    nameAr: 'الأحساء',
    nameEn: 'Al Ahsa',
    regionAr: 'المنطقة الشرقية',
    neighborhoods: ['الهفوف', 'المبرز', 'الخالدية', 'الشهابية'],
    isAvailable: true,
  },
  {
    id: 'taif',
    nameAr: 'الطائف',
    nameEn: 'Taif',
    regionAr: 'منطقة مكة المكرمة',
    neighborhoods: ['الشفا', 'الهدا', 'شهار', 'الحوية'],
    isAvailable: true,
  },
  {
    id: 'abha',
    nameAr: 'أبها',
    nameEn: 'Abha',
    regionAr: 'منطقة عسير',
    neighborhoods: ['السودة', 'الضباب', 'المفتاحة', 'المنسك'],
    isAvailable: true,
  },
  {
    id: 'tabuk',
    nameAr: 'تبوك',
    nameEn: 'Tabuk',
    regionAr: 'منطقة تبوك',
    neighborhoods: ['المروج', 'السليمانية', 'الورود', 'الأندلس'],
    isAvailable: true,
  },
];

export const OCCASION_TYPES: OccasionType[] = [
  {
    id: 'graduation',
    nameAr: 'تخرج',
    nameEn: 'Graduation',
    iconName: 'GraduationCap',
    categoryTag: 'academic',
    descriptionAr: 'احتفال بالتفوق ونيل الشهادات الدراسية مع الأهل والأصدقاء',
    popular: true,
    coverImage: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&auto=format&fit=crop&q=80',
    color: '#004D3F',
    suggestedServiceCategories: ['decor', 'hospitality', 'photography', 'cake', 'giveaways', 'invitations'],
    defaultChecklist: [
      { title: 'تحديد موعد ومكان الاحتفال والميزانية', daysBefore: 30, category: 'planning' },
      { title: 'حجز الكوشة وركن التصوير وخلفية التخرج', daysBefore: 20, category: 'decor' },
      { title: 'طلب كيكة التخرج وبوفيه الضيافة والحلويات', daysBefore: 15, category: 'hospitality' },
      { title: 'حجز مصورة متخصصة لتوثيق اللحظة', daysBefore: 14, category: 'photography' },
      { title: 'إرسال بطاقات الدعوة الرقمية عبر الواتساب', daysBefore: 10, category: 'invitations' },
      { title: 'تجهيز التوزيعات وعبارات الإهداء', daysBefore: 7, category: 'gifts' },
      { title: 'تأكيد الحضور النهائي واستلام المستلزمات', daysBefore: 2, category: 'final' }
    ]
  },
  {
    id: 'wedding',
    nameAr: 'زواج',
    nameEn: 'Wedding',
    iconName: 'HeartHandshake',
    categoryTag: 'wedding',
    descriptionAr: 'ليلة العمر بأعلى معايير الفخامة والضيافة السعودية الأصيلة',
    popular: true,
    coverImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
    color: '#C59B27',
    suggestedServiceCategories: ['venues', 'hospitality', 'decor', 'photography', 'entertainment', 'staff', 'lighting', 'invitations'],
    defaultChecklist: [
      { title: 'حجز قاعة الزفاف وتحديد عدد المدعوين', daysBefore: 90, category: 'venues' },
      { title: 'الاتفاق على تصميم الكوشة والممر والمدخل', daysBefore: 60, category: 'decor' },
      { title: 'حجز بوفيه العشاء والمباشرين والصبابين والذبائح', daysBefore: 45, category: 'hospitality' },
      { title: 'حجز استوديو التصوير والفيديو الاحترافي', daysBefore: 40, category: 'photography' },
      { title: 'اختيار وتجهيز الزفة والدي جي والفرقة الشعبية', daysBefore: 30, category: 'entertainment' },
      { title: 'تصميم وإرسال بطاقات الدعوة الذكية وتوليد QR', daysBefore: 20, category: 'invitations' },
      { title: 'توزيع الطاولات وتأكيد الحضور النهائي', daysBefore: 7, category: 'seating' },
      { title: 'المراجعة الميدانية مع مشرفي الحفل', daysBefore: 1, category: 'final' }
    ]
  },
  {
    id: 'melka',
    nameAr: 'ملكة / عقد قران',
    nameEn: 'Engagement / Melka',
    iconName: 'Sparkles',
    categoryTag: 'wedding',
    descriptionAr: 'أجواء عائلية حميمة ومبهجة لتوثيق عقد القران',
    popular: true,
    coverImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80',
    color: '#721C24',
    suggestedServiceCategories: ['decor', 'hospitality', 'photography', 'giveaways', 'invitations', 'beauty'],
    defaultChecklist: [
      { title: 'تحديد المكان (منزل / استراحة / قاعة خاصة)', daysBefore: 30, category: 'planning' },
      { title: 'اختيار طاولة عقد القران وتنسيق الورد والممر', daysBefore: 20, category: 'decor' },
      { title: 'حجز صبابين القهوة السعودية والمباشرات', daysBefore: 15, category: 'hospitality' },
      { title: 'حجز مصورة محترفة لتوثيق اللحظة والشبكة', daysBefore: 15, category: 'photography' },
      { title: 'إرسال الدعوات الرقمية واستقبال التأكيدات', daysBefore: 10, category: 'invitations' },
      { title: 'تجهيز البخور والعود وتوزيعات المعازيم', daysBefore: 5, category: 'hospitality' }
    ]
  },
  {
    id: 'newborn',
    nameAr: 'استقبال مولود جديد',
    nameEn: 'Newborn Welcome',
    iconName: 'Baby',
    categoryTag: 'family',
    descriptionAr: 'فرحة قدوم المولود الجديد مع أرق الديكورات وألذ التوزيعات',
    popular: true,
    coverImage: 'https://images.unsplash.com/photo-1555252333-978fead06c00?w=800&auto=format&fit=crop&q=80',
    color: '#2B6CB0',
    suggestedServiceCategories: ['decor', 'hospitality', 'giveaways', 'cake', 'invitations'],
    defaultChecklist: [
      { title: 'اختيار طابع الديكور وألوان استقبال المولود', daysBefore: 25, category: 'decor' },
      { title: 'طلب طاولات الشوكولاتة والتوزيعات المخصصة بالاسم', daysBefore: 20, category: 'giveaways' },
      { title: 'حجز خدمة القهوة السعودية والمشروبات الساخنة', daysBefore: 10, category: 'hospitality' },
      { title: 'تجهيز ركن الضيافة والموالح والحلويات', daysBefore: 5, category: 'hospitality' }
    ]
  },
  {
    id: 'birthday',
    nameAr: 'عيد ميلاد / حفلة أطفال',
    nameEn: 'Birthday & Kids Party',
    iconName: 'Cake',
    categoryTag: 'celebration',
    descriptionAr: 'أجواء مليئة بالمرح والبالونات والألعاب والفعاليات الممتعة',
    popular: true,
    coverImage: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&auto=format&fit=crop&q=80',
    color: '#D97706',
    suggestedServiceCategories: ['decor', 'cake', 'entertainment', 'photography', 'hospitality'],
    defaultChecklist: [
      { title: 'اختيار ثيم وشخصيات الحفلة', daysBefore: 20, category: 'decor' },
      { title: 'حجز فرقة الألعاب ومقدم الفعاليات', daysBefore: 15, category: 'entertainment' },
      { title: 'طلب كيكة الثيم وبوفيه الأطفال', daysBefore: 10, category: 'cake' },
      { title: 'إرسال بطاقات الدعوة المبهجة', daysBefore: 7, category: 'invitations' }
    ]
  },
  {
    id: 'national_day',
    nameAr: 'اليوم الوطني / يوم التأسيس',
    nameEn: 'National Day & Founding Day',
    iconName: 'Flag',
    categoryTag: 'national',
    descriptionAr: 'احتفالات وطنية تراثية فخمة، العرضة النجدية، والقهوة الأصيلة',
    popular: true,
    coverImage: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
    color: '#004D3F',
    suggestedServiceCategories: ['entertainment', 'hospitality', 'decor', 'lighting', 'giveaways'],
    defaultChecklist: [
      { title: 'حجز فرقة العرضة السعودية والفنون التراثية', daysBefore: 25, category: 'entertainment' },
      { title: 'تجهيز ديكور الأعلام والأزياء التراثية والخيمة', daysBefore: 20, category: 'decor' },
      { title: 'طلب بوفيه الأكلات السعودية والقهوة والتمر', daysBefore: 15, category: 'hospitality' },
      { title: 'توزيعات وهوية المناسبة الوطنية', daysBefore: 10, category: 'gifts' }
    ]
  },
  {
    id: 'family_gathering',
    nameAr: 'عزيمة / اجتماع عائلي',
    nameEn: 'Family Gathering & Azimah',
    iconName: 'Users',
    categoryTag: 'family',
    descriptionAr: 'ضيافة فاخرة وكرم سعودي أصيل لجمعات الأهل والأحباب',
    popular: false,
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    color: '#4A5568',
    suggestedServiceCategories: ['hospitality', 'staff', 'rentals', 'giveaways'],
    defaultChecklist: [
      { title: 'حجز الذبائح والعشاء النجدي/الحجازي', daysBefore: 10, category: 'hospitality' },
      { title: 'حجز قهوجيين وصبابين وتوفير البخور', daysBefore: 7, category: 'staff' },
      { title: 'تأكيد الجلسات الخارجية ومعدات التدفئة/التبريد', daysBefore: 4, category: 'rentals' }
    ]
  },
  {
    id: 'henna_night',
    nameAr: 'ليلة الحناء',
    nameEn: 'Henna Night',
    iconName: 'Palette',
    categoryTag: 'wedding',
    descriptionAr: 'ليلة تراثية غنائية نسائية مليئة بالبهجة والنقوش الشرقية',
    popular: false,
    coverImage: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    color: '#805AD5',
    suggestedServiceCategories: ['beauty', 'decor', 'hospitality', 'entertainment', 'photography'],
    defaultChecklist: [
      { title: 'حجز نقاشة حناء محترفة للمدعوات', daysBefore: 20, category: 'beauty' },
      { title: 'تجهيز الركن التراثي والمسند والمخاد الفلكلورية', daysBefore: 15, category: 'decor' },
      { title: 'حجز الدي جي والشيلات الشعبية النسائية', daysBefore: 12, category: 'entertainment' }
    ]
  },
  {
    id: 'corporate_opening',
    nameAr: 'افتتاح / حفل تكريم',
    nameEn: 'Grand Opening & Honor Event',
    iconName: 'Building',
    categoryTag: 'corporate',
    descriptionAr: 'تنظيم فعاليات الشركات والمعارض والافتتاحات الرسمية باحترافية',
    popular: false,
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    color: '#1A365D',
    suggestedServiceCategories: ['venues', 'lighting', 'staff', 'hospitality', 'photography'],
    defaultChecklist: [
      { title: 'تجهيز الشاشات والمسرح وأنظمة الصوت والترجمة', daysBefore: 25, category: 'lighting' },
      { title: 'حجز كوادر التنظيم والاستقبال ومضيفات الـ VIP', daysBefore: 20, category: 'staff' },
      { title: 'طلب الضيافة الفاخرة (Mocktails & Canapes)', daysBefore: 15, category: 'hospitality' }
    ]
  }
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'venues',
    nameAr: 'قاعات ومواقع فاخرة',
    nameEn: 'Venues & Halls',
    iconName: 'Building2',
    descriptionAr: 'قاعات أفراح، فنادق، شاليهات، استراحات، مزارع، وأسطح خاصة',
    color: '#004D3F',
    itemCount: 42,
  },
  {
    id: 'hospitality',
    nameAr: 'ضيافة وبوفيهات سعودية',
    nameEn: 'Saudi Hospitality & Catering',
    iconName: 'Coffee',
    descriptionAr: 'قهوجية، صبابين، ذبائح، بوفيه مفتوح، حلا قهوة، تمور، فود ترك',
    color: '#C59B27',
    itemCount: 88,
  },
  {
    id: 'decor',
    nameAr: 'كوش وديكور وتنسيق',
    nameEn: 'Kosha, Flowers & Decor',
    iconName: 'Flower2',
    descriptionAr: 'كوشات أعراس، تنسيق ورود طبيعية، بالونات، طاولات وممرات مداخل',
    color: '#E53E3E',
    itemCount: 65,
  },
  {
    id: 'photography',
    nameAr: 'تصوير وتوثيق احترافي',
    nameEn: 'Photography & Videography',
    iconName: 'Camera',
    descriptionAr: 'مصورات نساء، تصوير رجالي، درون، تعديل فوري، 360 Booth',
    color: '#3182CE',
    itemCount: 54,
  },
  {
    id: 'entertainment',
    nameAr: 'عروض وفنون وترفيه',
    nameEn: 'Entertainment & Ardah',
    iconName: 'Music',
    descriptionAr: 'عرضة سعودية، شيلات، دي جي، فرق شعبية، فعاليات أطفال ومسارح',
    color: '#805AD5',
    itemCount: 37,
  },
  {
    id: 'lighting',
    nameAr: 'صوت وإضاءة وشاشات',
    nameEn: 'Sound, Lighting & Screens',
    iconName: 'Lightbulb',
    descriptionAr: 'شاشات LED، إضاءات حفلات، ليزر، مكسرات صوت احترافية، مسارح',
    color: '#DD6B20',
    itemCount: 29,
  },
  {
    id: 'giveaways',
    nameAr: 'توزيعات وهدايا ضيوف',
    nameEn: 'Giveaways & Gifts',
    iconName: 'Gift',
    descriptionAr: 'توزيعات مخصصة بالاسم، عطور، مباخر، شوكولاتة فاخرة، وتذكارات',
    color: '#D69E2E',
    itemCount: 71,
  },
  {
    id: 'cake',
    nameAr: 'كيك وحلويات مناسبات',
    nameEn: 'Cakes & Sweet Tables',
    iconName: 'UtensilsCrossed',
    descriptionAr: 'كيكات تخرج، كيك أعراس، طاولات حلا، كوكيز مخصص، آيسكريم لايف',
    color: '#ED8936',
    itemCount: 45,
  },
  {
    id: 'invitations',
    nameAr: 'بطاقات ودعوات رقمية',
    nameEn: 'Digital Invites & RSVP',
    iconName: 'MailCheck',
    descriptionAr: 'دعوات واتساب تفاعلية، باركود QR، مواقع إلكترونية للمناسبة',
    color: '#319795',
    itemCount: 30,
  },
  {
    id: 'staff',
    nameAr: 'كوادر وتنظيم وصبابين',
    nameEn: 'Event Staff & Servers',
    iconName: 'Users2',
    descriptionAr: 'مباشرات نساء، صبابين رجال، مشرفات قاعة، حراسات أمنية، فاليه',
    color: '#4A5568',
    itemCount: 33,
  },
  {
    id: 'rentals',
    nameAr: 'تأجير مستلزمات وجلسات',
    nameEn: 'Rentals & Tents',
    iconName: 'Armchair',
    descriptionAr: 'طاولات نابليون، كراسي شفافة، خيام، دلال، مباخر عملاقة، مكيفات',
    color: '#718096',
    itemCount: 48,
  },
  {
    id: 'party_store',
    nameAr: 'متجر مستلزمات الحفلات',
    nameEn: 'Party Supplies Store',
    iconName: 'ShoppingBag',
    descriptionAr: 'أطباق فاخرة، شموع، لوحات ترحيبية أكريليك، لوازم تزيين فورية',
    color: '#4C51BF',
    itemCount: 92,
  },
];

export const VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    businessName: 'ضيافة نجد الأصيلة',
    businessNameEn: 'Najd Hospitality',
    categoryId: 'hospitality',
    categoryNameAr: 'ضيافة وبوفيهات سعودية',
    logo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewsCount: 184,
    completedBookingsCount: 320,
    verified: true,
    crNumber: '1010784920',
    vatNumber: '310984920100003',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'الملقا',
    serviceAreas: ['شمال الرياض', 'وسط الرياض', 'الدرعية', 'شرق الرياض'],
    startingPrice: 1200,
    instantBooking: true,
    responseTimeMinutes: 8,
    badges: ['موثق بسجل تجاري', 'الأعلى تقييماً', 'حجز فوري', 'ضيافة ملكية'],
    bioAr: 'نقدم أرقى خدمات القهوة السعودية والهيل الفاخر والتمور الملكية مع كادر صبابين ومباشرين ومباشرات بزي سعودي تراثي أنيق.',
    portfolio: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966501234567',
    whatsappNumber: '966501234567',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء مجاني حتى 5 أيام قبل موعد المناسبة مع استرداد كامل العربون.',
    status: 'active',
  },
  {
    id: 'vendor-2',
    businessName: 'كوشة وفرح لتنسيق الحفلات',
    businessNameEn: 'Kosha & Farah Decor',
    categoryId: 'decor',
    categoryNameAr: 'كوش وديكور وتنسيق',
    logo: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&auto=format&fit=crop&q=80',
    rating: 4.88,
    reviewsCount: 142,
    completedBookingsCount: 215,
    verified: true,
    crNumber: '1010992381',
    vatNumber: '310492817200003',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'الياسمين',
    serviceAreas: ['كافة أحياء الرياض', 'الخرج', 'المجمعة'],
    startingPrice: 3500,
    instantBooking: false,
    responseTimeMinutes: 15,
    badges: ['موثق بسجل تجاري', 'تصاميم حصرية', 'تنفيذ دقيق'],
    bioAr: 'متخصصون في ابتكار كوش الأعراس والمناسبات الفاخرة وخلفيات التخرج والملكة، وتنسيق الزهور الطبيعية الهولندية والمدخل الاستثنائي.',
    portfolio: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966507654321',
    whatsappNumber: '966507654321',
    genderSpecialty: 'women_specialist',
    cancellationPolicyAr: 'إلغاء مرن حتى 7 أيام قبل المناسبة.',
    status: 'active',
  },
  {
    id: 'vendor-3',
    businessName: 'استوديو وميض (تصوير نسائي ورجالي)',
    businessNameEn: 'Wameed Media Studio',
    categoryId: 'photography',
    categoryNameAr: 'تصوير وتوثيق احترافي',
    logo: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=1200&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewsCount: 96,
    completedBookingsCount: 168,
    verified: true,
    freelanceLicense: 'FL-92837190',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'حطين',
    serviceAreas: ['الرياض', 'جدة', 'الشرقية'],
    startingPrice: 2000,
    instantBooking: true,
    responseTimeMinutes: 10,
    badges: ['موثق بوثيقة عمل حر', 'طاقم نسائي معتمد', 'تسليم سريع'],
    bioAr: 'طاقم تصوير نسائي ورجالي مجهز بأحدث كاميرات السينما والدرون، مع مونتاج سينمائي وتسليم ألبوم إيطالي فاخر في غضون 7 أيام.',
    portfolio: [
      'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966559876543',
    whatsappNumber: '966559876543',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء متاح حتى 10 أيام قبل الموعد.',
    status: 'active',
  },
  {
    id: 'vendor-4',
    businessName: 'قصر الفيروز للاحتفالات والمؤتمرات',
    businessNameEn: 'Al Fayrouz Palace Hall',
    categoryId: 'venues',
    categoryNameAr: 'قاعات ومواقع فاخرة',
    logo: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1200&auto=format&fit=crop&q=80',
    rating: 4.85,
    reviewsCount: 210,
    completedBookingsCount: 450,
    verified: true,
    crNumber: '1010443210',
    vatNumber: '310884920100003',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'الرمال',
    serviceAreas: ['الرياض'],
    startingPrice: 18000,
    instantBooking: false,
    responseTimeMinutes: 20,
    badges: ['قاعات رجال ونساء منفصلة', 'مدخل مستقل', 'جناح عروس خاص', 'مواقف VIP'],
    bioAr: 'قصر احتفالات متكامل يتسع لـ 500 شخص مع قسمين مستقلين للرجال والنساء، غرف تبديل، وأنظمة إضاءة ومسارح ومطابخ ذبائح مركزية.',
    portfolio: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966541122334',
    whatsappNumber: '966541122334',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'تطبق سياسة الحجز المعتمدة للقاعات.',
    status: 'active',
  },
  {
    id: 'vendor-5',
    businessName: 'حلويات وشوكولاتة لافندر سويتس',
    businessNameEn: 'Lavender Sweets & Cakes',
    categoryId: 'cake',
    categoryNameAr: 'كيك وحلويات مناسبات',
    logo: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=1200&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewsCount: 312,
    completedBookingsCount: 580,
    verified: true,
    crNumber: '1010332211',
    vatNumber: '310223344500003',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'النرجس',
    serviceAreas: ['كافة أحياء الرياض'],
    startingPrice: 650,
    instantBooking: true,
    responseTimeMinutes: 5,
    badges: ['كيك حسب الطلب', 'طعم استثنائي', 'توصيل مبرد'],
    bioAr: 'كيكات فنية بطبقات الشوكولاتة البلجيكية والكراميل المملح، وصواني حلا مخصصة بأسماء الخريجين والعرسان.',
    portfolio: [
      'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966567788990',
    whatsappNumber: '966567788990',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'تعديل أو إلغاء مجاني قبل 3 أيام من التسليم.',
    status: 'active',
  },
  {
    id: 'vendor-6',
    businessName: 'فرقة سيوف نجد للعرضة والفنون التراثية',
    businessNameEn: 'Suyoof Najd Folk & Ardah',
    categoryId: 'entertainment',
    categoryNameAr: 'عروض وفنون وترفيه',
    logo: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=1200&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewsCount: 164,
    completedBookingsCount: 290,
    verified: true,
    crNumber: '1010556677',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'الدرعية',
    serviceAreas: ['منطقة الرياض', 'القصيم', 'الشرقية'],
    startingPrice: 3000,
    instantBooking: false,
    responseTimeMinutes: 12,
    badges: ['فرقة عرضة رسمية', 'لباس سعودي أصيل', 'طبول وسيوف مذهبة'],
    bioAr: 'أقوى عروض العرضة السعودية النجدية والسامري وشيلات الترحيب مع عازفين ومؤدين محترفين يرفعون رأسك أمام ضيوفك.',
    portfolio: [
      'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966533344455',
    whatsappNumber: '966533344455',
    genderSpecialty: 'men_specialist',
    cancellationPolicyAr: 'إلغاء متاح قبل أسبوع من المناسبة.',
    status: 'active',
  },
  {
    id: 'vendor-7',
    businessName: 'دار البخور والعود الملكي',
    businessNameEn: 'Royal Oud & Incense',
    categoryId: 'giveaways',
    categoryNameAr: 'توزيعات وهدايا ضيوف',
    logo: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=1200&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewsCount: 180,
    completedBookingsCount: 410,
    verified: true,
    crNumber: '1010887766',
    vatNumber: '310998877600003',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'العليا',
    serviceAreas: ['كافة مدن المملكة'],
    startingPrice: 850,
    instantBooking: true,
    responseTimeMinutes: 6,
    badges: ['عود موروكي فاخر', 'تغليف ملكي بالاسم', 'شحن مبرد'],
    bioAr: 'توزيعات أعراس وتخرج راقية تحتوي على تولات عود طبيعي، رقائق عود موروكي، ومباخر ذكية منقوشة بالليزر مع كروت إهداء ذهبية.',
    portfolio: [
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966599988877',
    whatsappNumber: '966599988877',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'استرجاع فوري قبل البدء بالطباعة والتخصيص.',
    status: 'active',
  },
  {
    id: 'vendor-8',
    businessName: 'استوديو لمسات العروس (جدة)',
    businessNameEn: 'Lamasat Bride Studio',
    categoryId: 'photography',
    categoryNameAr: 'تصوير وتوثيق احترافي',
    logo: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&auto=format&fit=crop&q=80',
    rating: 4.97,
    reviewsCount: 125,
    completedBookingsCount: 195,
    verified: true,
    freelanceLicense: 'FL-88192031',
    cityId: 'jeddah',
    cityNameAr: 'جدة',
    neighborhood: 'الشاطئ',
    serviceAreas: ['جدة', 'مكة المكرمة', 'المدينة المنورة'],
    startingPrice: 3200,
    instantBooking: true,
    responseTimeMinutes: 10,
    badges: ['طاقم نسائي 100%', 'خصوصية تامة', 'تصوير سينمائي'],
    bioAr: 'نقدم للمناسبات النسائية بجدة ومكة أعلى درجات الخصوصية والاحترافية في تصوير حفلات الملكة والزواج والتخرج.',
    portfolio: [
      'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966522233344',
    whatsappNumber: '966522233344',
    genderSpecialty: 'women_specialist',
    cancellationPolicyAr: 'إلغاء مجاني قبل أسبوعين من الحفل.',
    status: 'active',
  },
  {
    id: 'vendor-9',
    businessName: 'قصر ليلتي للاحتفالات الملكية',
    businessNameEn: 'Laylaty Grand Ballroom',
    categoryId: 'venues',
    categoryNameAr: 'قاعات ومواقع فاخرة',
    logo: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=1200&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewsCount: 280,
    completedBookingsCount: 520,
    verified: true,
    crNumber: '4030192837',
    vatNumber: '310892817200003',
    cityId: 'jeddah',
    cityNameAr: 'جدة',
    neighborhood: 'أبحر الشمالية',
    serviceAreas: ['جدة', 'مكة المكرمة'],
    startingPrice: 22000,
    instantBooking: false,
    responseTimeMinutes: 15,
    badges: ['إطلالة بحرية', 'قاعات ملكية فسيحة', 'خدمة فندقية 5 نجوم', 'مواقف خاصة'],
    bioAr: 'أفخم قاعات الأعراس في عروس البحر الأحمر جدة بتصاميم كلاسيكية مذهبة، ثريات كريستال عملاقة، وأجنحة ملكية خاصة بالعروسين.',
    portfolio: [
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966523344556',
    whatsappNumber: '966523344556',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'تطبق سياسة الحجوزات الرسمية للقاعات الكبرى.',
    status: 'active',
  },
  {
    id: 'vendor-10',
    businessName: 'مطابخ الريف الحجازي للبوفيهات والذبائح',
    businessNameEn: 'Al Reef Hijazi Catering',
    categoryId: 'hospitality',
    categoryNameAr: 'ضيافة وبوفيهات سعودية',
    logo: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=1200&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewsCount: 195,
    completedBookingsCount: 380,
    verified: true,
    crNumber: '4030882190',
    vatNumber: '310488219000003',
    cityId: 'jeddah',
    cityNameAr: 'جدة',
    neighborhood: 'الروضة',
    serviceAreas: ['جدة', 'مكة المكرمة', 'الطائف'],
    startingPrice: 3800,
    instantBooking: true,
    responseTimeMinutes: 8,
    badges: ['سليق طائفي أصيل', 'بوفيهات حجازية وعالمية', 'ذبائح حرية طازجة'],
    bioAr: 'إعداد أشهى الولائم الحجازية والنجدية (السليق، الكابلي، المندي، والمفطح) مع بوفيهات مقبلات وسلطات باردة وحارة وحلويات شرقية.',
    portfolio: [
      'https://images.unsplash.com/photo-1555244162-803834f70033?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966524455667',
    whatsappNumber: '966524455667',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء مجاني قبل 4 أيام من تاريخ المناسبة.',
    status: 'active',
  },
  {
    id: 'vendor-11',
    businessName: 'فلورا آرت لتنسيق الكوش والزهور الفاخرة',
    businessNameEn: 'Flora Art Events Decor',
    categoryId: 'decor',
    categoryNameAr: 'كوش وديكور وتنسيق',
    logo: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&auto=format&fit=crop&q=80',
    rating: 4.94,
    reviewsCount: 168,
    completedBookingsCount: 260,
    verified: true,
    crNumber: '2051092834',
    vatNumber: '310209283400003',
    cityId: 'khobar',
    cityNameAr: 'الخبر',
    neighborhood: 'الحزام الذهبي',
    serviceAreas: ['الخبر', 'الدمام', 'الظهران', 'الأحساء', 'الجبيل'],
    startingPrice: 4200,
    instantBooking: false,
    responseTimeMinutes: 12,
    badges: ['تصاميم 3D مسبقة', 'زهور طبيعية مستوردة', 'تنفيذ هندسي دقيق'],
    bioAr: 'تصميم وتنفيذ كوش الأعراس وطاولات الاستقبال الملكية بالمنطقة الشرقية باستخدام أحدث تقنيات الإضاءة والمرايا والزهور الهولندية.',
    portfolio: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966535566778',
    whatsappNumber: '966535566778',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء مجاني قبل أسبوع من المناسبة.',
    status: 'active',
  },
  {
    id: 'vendor-12',
    businessName: 'فرقة أنغام الحجاز للمجرور والمزمار والعرضة',
    businessNameEn: 'Angham Hijaz Folk Arts',
    categoryId: 'entertainment',
    categoryNameAr: 'عروض وفنون وترفيه',
    logo: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewsCount: 140,
    completedBookingsCount: 230,
    verified: true,
    crNumber: '4030991283',
    cityId: 'makkah',
    cityNameAr: 'مكة المكرمة',
    neighborhood: 'العزيزية',
    serviceAreas: ['مكة المكرمة', 'جدة', 'الطائف', 'المدينة المنورة'],
    startingPrice: 3500,
    instantBooking: false,
    responseTimeMinutes: 10,
    badges: ['فن المزمار الحجازي', 'مجرور طائفي', 'عرضة سعودية', 'أزياء حجازية تراثية'],
    bioAr: 'إحياء ليالي الأعراس والملكات والمناسبات الوطنية بأعذب الفنون الشعبية الحجازية الأصيلة (المزمار، المجرور، الخبيتي، والينبعاوي).',
    portfolio: [
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966546677889',
    whatsappNumber: '966546677889',
    genderSpecialty: 'men_specialist',
    cancellationPolicyAr: 'إلغاء متاح قبل 10 أيام من الموعد.',
    status: 'active',
  },
  {
    id: 'vendor-13',
    businessName: 'تمور ومباخر هجر الفاخرة',
    businessNameEn: 'Hajar Luxury Dates & Incense',
    categoryId: 'giveaways',
    categoryNameAr: 'توزيعات وهدايا ضيوف',
    logo: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=1200&auto=format&fit=crop&q=80',
    rating: 4.97,
    reviewsCount: 220,
    completedBookingsCount: 460,
    verified: true,
    crNumber: '2251093821',
    vatNumber: '310225109300003',
    cityId: 'ahsa',
    cityNameAr: 'الأحساء',
    neighborhood: 'الهفوف',
    serviceAreas: ['الأحساء', 'الدمام', 'الخبر', 'كافة مدن المملكة'],
    startingPrice: 950,
    instantBooking: true,
    responseTimeMinutes: 5,
    badges: ['خلاص أحسائي فاخر', 'مباخر خشبية مخصصة', 'تغليف سدو تراثي'],
    bioAr: 'أجود أنواع التمر الخلاص الأحسائي الملكي المحشو بالهيل والمكسرات، مع مباخر وتوزيعات عود منقوشة بأسماء العرسان أو الخريجين.',
    portfolio: [
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966557788990',
    whatsappNumber: '966557788990',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء فوري قبل بدء التخصيص بالليزر.',
    status: 'active',
  },
  {
    id: 'vendor-14',
    businessName: 'استوديو أضواء الجنوب للتصوير السينمائي',
    businessNameEn: 'Adwaa Al Janoob Studios',
    categoryId: 'photography',
    categoryNameAr: 'تصوير وتوثيق احترافي',
    logo: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=1200&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewsCount: 110,
    completedBookingsCount: 185,
    verified: true,
    freelanceLicense: 'FL-77192084',
    cityId: 'abha',
    cityNameAr: 'أبها',
    neighborhood: 'السودة',
    serviceAreas: ['أبها', 'خميس مشيط', 'جازان', 'نجران', 'الباحة'],
    startingPrice: 2400,
    instantBooking: true,
    responseTimeMinutes: 10,
    badges: ['توثيق سينمائي 4K', 'طاقم نسائي معتمد', 'تصوير درون في الطبيعة'],
    bioAr: 'توثيق سينمائي فاخر للأعراس والمناسبات العائلية في منطقة عسير والجنوب، مع جلسات تصوير خارجية بين غيوم السودة وطبيعة الجنوب الخلابة.',
    portfolio: [
      'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966568899001',
    whatsappNumber: '966568899001',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء مجاني قبل 10 أيام من المناسبة.',
    status: 'active',
  },
  {
    id: 'vendor-15',
    businessName: 'منتجع ومخيمات واحة العلا للمناسبات الخاصة',
    businessNameEn: 'AlUla Oasis Luxury Events',
    categoryId: 'venues',
    categoryNameAr: 'قاعات ومواقع فاخرة',
    logo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    rating: 4.99,
    reviewsCount: 88,
    completedBookingsCount: 145,
    verified: true,
    crNumber: '3550192834',
    vatNumber: '310355019200003',
    cityId: 'alula',
    cityNameAr: 'العلا',
    neighborhood: 'البلدة القديمة',
    serviceAreas: ['العلا', 'المدينة المنورة', 'تبوك'],
    startingPrice: 15000,
    instantBooking: false,
    responseTimeMinutes: 15,
    badges: ['بين جبال العلا الساحرة', 'تجهيزات ملكية', 'إضاءات فلكية تحت النجوم'],
    bioAr: 'تنظيم أفخم المناسبات الخاصة، وحفلات الزواج الحصرية، والاجتماعات الرفيعة بين جبال وتاريخ العلا الفريد مع تجربة ضيافة استثنائية.',
    portfolio: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966579900112',
    whatsappNumber: '966579900112',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'تطبق سياسة الحجز الحصري لمواقع العلا.',
    status: 'active',
  },
  {
    id: 'vendor-16',
    businessName: 'ريماس للشوكولاتة البلجيكية وكيك المناسبات',
    businessNameEn: 'Rimas Chocolate & Event Cakes',
    categoryId: 'cake',
    categoryNameAr: 'كيك وحلويات مناسبات',
    logo: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=1200&auto=format&fit=crop&q=80',
    rating: 4.91,
    reviewsCount: 175,
    completedBookingsCount: 340,
    verified: true,
    crNumber: '4650192834',
    vatNumber: '310465019200003',
    cityId: 'madinah',
    cityNameAr: 'المدينة المنورة',
    neighborhood: 'سلطانة',
    serviceAreas: ['المدينة المنورة', 'ينبع'],
    startingPrice: 750,
    instantBooking: true,
    responseTimeMinutes: 6,
    badges: ['شوكولاتة بلجيكية فاخرة', 'كيكات أدوار متعددة', 'طاولات استقبال متكاملة'],
    bioAr: 'إبداع في كيكات الزفاف والملكة الفاخرة وصواني الشوكولاتة المطبوعة بالأسماء والعبارات الترحيبية لأهل المدينة وزوارها.',
    portfolio: [
      'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966580011223',
    whatsappNumber: '966580011223',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'تعديل مجاني قبل 3 أيام من التسليم.',
    status: 'active',
  },
  {
    id: 'vendor-17',
    businessName: 'دلة الفخامة لصبابين القهوة والمباشرين',
    businessNameEn: 'Dallah Al Fakhama Hospitality',
    categoryId: 'hospitality',
    categoryNameAr: 'ضيافة وبوفيهات سعودية',
    logo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=1200&auto=format&fit=crop&q=80',
    rating: 4.94,
    reviewsCount: 155,
    completedBookingsCount: 310,
    verified: true,
    crNumber: '2050192834',
    vatNumber: '310205019200003',
    cityId: 'dammam',
    cityNameAr: 'الدمام',
    neighborhood: 'الشاطئ الغربي',
    serviceAreas: ['الدمام', 'الخبر', 'الظهران', 'القطيف', 'رأس تنورة'],
    startingPrice: 1400,
    instantBooking: true,
    responseTimeMinutes: 7,
    badges: ['صبابين ومباشرات بالزي الرسمي', 'قهوة هيل وزعفران', 'مباخر وبخور كمبودي'],
    bioAr: 'كرم الضيافة السعودية الأصيلة في الشرقية، قهوجية ومباشرين ومباشرات بأعلى درجات اللباقة والزي الموحد الأنيق ودلال رسلان النحاسية.',
    portfolio: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966591122334',
    whatsappNumber: '966591122334',
    genderSpecialty: 'both',
    cancellationPolicyAr: 'إلغاء مجاني حتى 4 أيام قبل المناسبة.',
    status: 'active',
  },
  {
    id: 'vendor-18',
    businessName: 'فرقة صدى الجنوب للخطوة والعرضة الجنوبية',
    businessNameEn: 'Sada Al Janoob Folk Group',
    categoryId: 'entertainment',
    categoryNameAr: 'عروض وفنون وترفيه',
    logo: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=300&auto=format&fit=crop&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=1200&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewsCount: 130,
    completedBookingsCount: 220,
    verified: true,
    crNumber: '5850192834',
    cityId: 'abha',
    cityNameAr: 'أبها',
    neighborhood: 'المفتاحة',
    serviceAreas: ['أبها', 'خميس مشيط', 'جازان', 'نجران', 'الباحة'],
    startingPrice: 2800,
    instantBooking: false,
    responseTimeMinutes: 12,
    badges: ['الخطوة العسيرية الأصيلة', 'الزامل والشيلات', 'أزياء جنوبية تراثية بالخناجر'],
    bioAr: 'أقوى أداء للخطوة الجنوبية والعرضة والشيلات الحماسية التراثية لإشعال الفرح ورفع رؤوس أهل الحفل في كافة مدن الجنوب.',
    portfolio: [
      'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
    ],
    contactPhone: '+966502233445',
    whatsappNumber: '966502233445',
    genderSpecialty: 'men_specialist',
    cancellationPolicyAr: 'إلغاء متاح قبل أسبوع من المناسبة.',
    status: 'active',
  }
];

export const SERVICE_ITEMS: ServiceItem[] = [
  {
    id: 'srv-1',
    vendorId: 'vendor-1',
    vendorName: 'ضيافة نجد الأصيلة',
    vendorRating: 4.95,
    vendorLogo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
    categoryId: 'hospitality',
    categoryNameAr: 'ضيافة وبوفيهات سعودية',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    titleAr: 'خدمة ضيافة القهوة السعودية الملكية والتمور (50 - 80 شخص)',
    descriptionAr: 'تشمل قهوة شقراء بالزعفران والهيل، دلال رسلان مذهبة، تمور سكري مفتل محشية مكسرات، 2 صبابين/مباشرات بزي تراثي كامل، مع مباخر عود.',
    price: 1650,
    priceType: 'fixed',
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
    ],
    featuresAr: ['2 صبابين / صبابات بزي موحد', 'دلال رسلان نحاسية فاخرة', 'تمر سكري محشي ومكسرات', 'شاي كرك وشاي بالنعناع الحساوي', 'تبخير مستمر بدهن العود'],
    capacityMax: 80,
    instantBooking: true,
    genderPreference: 'unisex',
    badge: 'الأكثر طلباً',
    isPopular: true,
  },
  {
    id: 'srv-2',
    vendorId: 'vendor-2',
    vendorName: 'كوشة وفرح لتنسيق الحفلات',
    vendorRating: 4.88,
    vendorLogo: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=300&auto=format&fit=crop&q=80',
    categoryId: 'decor',
    categoryNameAr: 'كوش وديكور وتنسيق',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    titleAr: 'كوشة تخرج وملكة فاخرة مع خلفية أكريليك وورد طبيعي 4 متر',
    descriptionAr: 'تصميم أنيق متكامل يشمل خلفية دائرية أو مستطيلة مع لوحة اسم مضيئة LED، تنسيق أزهار طبيعية هولندية، كراسي ملكية، وإضاءة سبوت لايت دافئة.',
    price: 3800,
    priceType: 'fixed',
    images: [
      'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80',
    ],
    featuresAr: ['خلفية 4 متر مع اسم الخريج/العروسين', 'ورود طبيعية ألوان مختارة', 'إضاءات سبوت لايت دافئة', 'طاولة كيك وأعمدة ستاندات', 'شامل النقل والتركيب والإزالة'],
    capacityMax: 150,
    instantBooking: false,
    genderPreference: 'women',
    badge: 'تصميم مميز',
    isPopular: true,
  },
  {
    id: 'srv-3',
    vendorId: 'vendor-3',
    vendorName: 'استوديو وميض (تصوير نسائي ورجالي)',
    vendorRating: 4.92,
    vendorLogo: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=300&auto=format&fit=crop&q=80',
    categoryId: 'photography',
    categoryNameAr: 'تصوير وتوثيق احترافي',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    titleAr: 'باقة تصوير المناسبات والتخرج VIP (فوتوغراف + فيديو سينمائي)',
    descriptionAr: 'تغطية 4 ساعات مع مصورة فوتوغراف ومصورة فيديو، جلسة تصوير خاصة مع الأهل، مونتاج فيديو ريلز دقيقة، وتسليم كافة الصور معدلة مع ألبوم جلد.',
    price: 2400,
    priceType: 'fixed',
    images: [
      'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=800&auto=format&fit=crop&q=80',
    ],
    featuresAr: ['مصورة فوتوغراف + مصورة فيديو', 'تغطية 4 ساعات كاملة', 'ألبوم حراري إيطالي مقاس 30x40', 'فيديو ريلز إنستغرام سينمائي', 'فلاش ميموري بجميع الصور عالية الدقة'],
    instantBooking: true,
    genderPreference: 'women',
    badge: 'حجز فوري',
    isPopular: true,
  },
  {
    id: 'srv-4',
    vendorId: 'vendor-5',
    vendorName: 'حلويات وشوكولاتة لافندر سويتس',
    vendorRating: 4.96,
    vendorLogo: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=300&auto=format&fit=crop&q=80',
    categoryId: 'cake',
    categoryNameAr: 'كيك وحلويات مناسبات',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    titleAr: 'كيكة مناسبات 3 طبقات مخصصة + 60 قطعة حلا ميني كاسات',
    descriptionAr: 'كيكة فخمة مغطاة بعجينة السكر ومزينة بزهور السكر ورسائل التهنئة، مع 60 كاسة حلا منوعة (تشيز كيك لوتس، كراميل فستق، شوكولاتة كرانشي).',
    price: 1400,
    priceType: 'fixed',
    images: [
      'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&auto=format&fit=crop&q=80',
    ],
    featuresAr: ['كيكة 3 طبقات تكفي 60 شخص', 'نكهات مخصصة حسب اختيارك', '60 كاسة حلا تقديم أنيقة', 'كتابة الاسم والشعار مجاناً', 'توصيل مبرد لباب القاعة'],
    instantBooking: true,
    genderPreference: 'unisex',
    badge: 'فاخر',
    isPopular: false,
  },
  {
    id: 'srv-5',
    vendorId: 'vendor-7',
    vendorName: 'دار البخور والعود الملكي',
    vendorRating: 4.91,
    vendorLogo: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=300&auto=format&fit=crop&q=80',
    categoryId: 'giveaways',
    categoryNameAr: 'توزيعات وهدايا ضيوف',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    titleAr: 'بوكس توزيعات العود والمباخر المذهبة (50 حبة مع بطاقة الاسم)',
    descriptionAr: '50 بوكس فاخر يحتوي كل منها على مبخرة سيراميك منقوشة بالذهب، تولة عود كمبودي معتق، وكسرة عود موروكي VIP مع بطاقة إهداء مخصصة.',
    price: 1750,
    priceType: 'fixed',
    images: [
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&auto=format&fit=crop&q=80',
    ],
    featuresAr: ['50 حبة جاهزة للتوزيع', 'تولة عود طبيعي فاخر', 'مبخرة ذهبية أنيقة', 'طباعة أسماء العرسان/الخريج بالذهب', 'صندوق تقديم كريستالي مجاني'],
    instantBooking: true,
    genderPreference: 'unisex',
    badge: 'توفير خاص',
    isPopular: true,
  },
  {
    id: 'srv-6',
    vendorId: 'vendor-6',
    vendorName: 'فرقة سيوف نجد للعرضة والفنون التراثية',
    vendorRating: 4.98,
    vendorLogo: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=300&auto=format&fit=crop&q=80',
    categoryId: 'entertainment',
    categoryNameAr: 'عروض وفنون وترفيه',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    titleAr: 'عرضة سعودية نجدية وسامري كامل (طاقم 12 مؤدي بالسيف والطبول)',
    descriptionAr: 'استقبال ضيوف فاخر مع أداء العرضة النجدية الرسمية، وشيلات ترحيبية خاصة بصاحب الحفل، مع سامري حماسي يلهب الأجواء.',
    price: 4500,
    priceType: 'fixed',
    images: [
      'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
    ],
    featuresAr: ['12 مؤدي وعازف بزي تراثي موحد', 'سيوف وطبول مذهبة', 'أشعار وشيلات خاصة بالاسم', 'تغطية استقبال الضيوف والزفة', 'مدة العرض ساعتين ونصف'],
    instantBooking: false,
    genderPreference: 'men',
    badge: 'أعلى تقييم',
    isPopular: true,
  }
];

export const SMART_PACKAGES: SmartPackage[] = [
  {
    id: 'pkg-grad-50',
    titleAr: 'باقة التخرج المتكاملة VIP (50 شخص)',
    subtitleAr: 'كل ما تحتاجه لحفلة تخرج لا تُنسى في بكج واحد مع توفير 2,200 ريال',
    occasionTypeId: 'graduation',
    occasionTypeNameAr: 'تخرج',
    cityId: 'riyadh',
    guestCount: 50,
    originalPrice: 11200,
    packagePrice: 9000,
    savings: 2200,
    badge: 'الأكثر مبيعاً 🌟',
    image: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&auto=format&fit=crop&q=80',
    rating: 4.96,
    reviewsCount: 88,
    descriptionAr: 'باقة صُممت بعناية لتغطي كامل متطلبات حفل التخرج الفاخر لـ 50 شخصاً، من الكوشة والتصوير والضيافة وحتى التوزيعات والدعوات الرقمية.',
    customizable: true,
    items: [
      {
        categoryName: 'كوش وديكور',
        serviceName: 'كوشة تخرج أكريليك مع ورد طبيعي وبورد ترحيبي',
        vendorName: 'كوشة وفرح لتنسيق الحفلات',
        vendorId: 'vendor-2',
        pricePortion: 3500,
        included: true,
        customizable: true,
        options: ['ورد أبيض وذهبي', 'ورد وردي وسماوي', 'ثيم كحلي وذهبي']
      },
      {
        categoryName: 'تصوير وتوثيق',
        serviceName: 'تغطية تصوير فوتوغرافي وفيديو 3 ساعات + ألبوم',
        vendorName: 'استوديو وميض',
        vendorId: 'vendor-3',
        pricePortion: 2000,
        included: true,
        customizable: true
      },
      {
        categoryName: 'ضيافة وقهوجية',
        serviceName: 'ضيافة قهوة سعودية وشاي مع صبابات وتمور فاخرة',
        vendorName: 'ضيافة نجد الأصيلة',
        vendorId: 'vendor-1',
        pricePortion: 1500,
        included: true,
        customizable: true
      },
      {
        categoryName: 'كيك وحلويات',
        serviceName: 'كيكة تخرج مخصصة بالاسم + 50 كاسة حلا تقديم',
        vendorName: 'حلويات لافندر سويتس',
        vendorId: 'vendor-5',
        pricePortion: 1200,
        included: true,
        customizable: true
      },
      {
        categoryName: 'توزيعات وهدايا',
        serviceName: '50 بوكس عود موروكي ومباخر منقوشة بالاسم',
        vendorName: 'دار البخور والعود الملكي',
        vendorId: 'vendor-7',
        pricePortion: 1400,
        included: true,
        customizable: true
      },
      {
        categoryName: 'دعوات رقمية',
        serviceName: 'نظام دعوة واتساب تفاعلية مع كود QR لتأكيد الحضور',
        vendorName: 'منصة مناسبتي الرقمية',
        vendorId: 'vendor-internal',
        pricePortion: 400,
        included: true,
        customizable: false
      }
    ]
  },
  {
    id: 'pkg-melka-60',
    titleAr: 'باقة الملكة المنزلية الراقية (60 شخص)',
    subtitleAr: 'ترتيبات عقد القران والشبكة الفاخرة بلمسة تراثية عصرية',
    occasionTypeId: 'melka',
    occasionTypeNameAr: 'ملكة / عقد قران',
    cityId: 'riyadh',
    guestCount: 60,
    originalPrice: 15800,
    packagePrice: 12900,
    savings: 2900,
    badge: 'اختيار العرائس 💍',
    image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80',
    rating: 4.93,
    reviewsCount: 64,
    descriptionAr: 'كل ما يلزم لعقد قران واستقبال شبكة مميز في المنزل أو الاستراحة الخاصة بأجواء شاعرية وتنسيق أزهار طبيعية عالي الجودة.',
    customizable: true,
    items: [
      {
        categoryName: 'كوش وديكور',
        serviceName: 'طاولة عقد القران الملكية مع قوس الورد الطبيعي والممر',
        vendorName: 'كوشة وفرح لتنسيق الحفلات',
        vendorId: 'vendor-2',
        pricePortion: 4500,
        included: true,
        customizable: true
      },
      {
        categoryName: 'تصوير وتوثيق',
        serviceName: 'مصورة نسائية محترفة لتوثيق عقد القران وتلبيس الشبكة',
        vendorName: 'استوديو وميض',
        vendorId: 'vendor-3',
        pricePortion: 2400,
        included: true,
        customizable: true
      },
      {
        categoryName: 'ضيافة وبوفيه',
        serviceName: 'ركن الضيافة النجدية + صينية معجنات وموالح فرنسية فاخرة',
        vendorName: 'ضيافة نجد الأصيلة',
        vendorId: 'vendor-1',
        pricePortion: 2200,
        included: true,
        customizable: true
      },
      {
        categoryName: 'توزيعات وهدايا',
        serviceName: '60 حبة توزيعات مباخر سيراميك ومسك العروس',
        vendorName: 'دار البخور والعود الملكي',
        vendorId: 'vendor-7',
        pricePortion: 1800,
        included: true,
        customizable: true
      },
      {
        categoryName: 'كيك وحلويات',
        serviceName: 'كيكة ملكة دورين بطابع الورد الطبيعي والذهب الصالح للأكل',
        vendorName: 'حلويات لافندر سويتس',
        vendorId: 'vendor-5',
        pricePortion: 1500,
        included: true,
        customizable: true
      },
      {
        categoryName: 'دعوات وتأكيد الحضور',
        serviceName: 'بطاقة دعوة متحركة فاخرة مع رابط RSVP',
        vendorName: 'منصة مناسبتي الرقمية',
        vendorId: 'vendor-internal',
        pricePortion: 500,
        included: true,
        customizable: false
      }
    ]
  },
  {
    id: 'pkg-wedding-200',
    titleAr: 'باقة الزفاف الملكي الشاملة (200 شخص)',
    subtitleAr: 'تنظيم زفاف كامل من القاعة إلى بوفيه الذبائح والعرضة والتوثيق السينمائي',
    occasionTypeId: 'wedding',
    occasionTypeNameAr: 'زواج',
    cityId: 'riyadh',
    guestCount: 200,
    originalPrice: 48000,
    packagePrice: 39500,
    savings: 8500,
    badge: 'الفخامة الملكية 👑',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewsCount: 42,
    descriptionAr: 'الباقة الكبرى للأعراس السعودية: تجهيز قاعة كاملة، كوشة ملكية عملاقة، تصوير 4 كاميرات مع درون، عرضة نجدية، بوفيه مفتوح وصبابين للقسمين.',
    customizable: true,
    items: [
      {
        categoryName: 'كوش وديكور',
        serviceName: 'كوشة زفاف ملكية 8 أمتار وممر مضيء وطاولات معازيم VIP',
        vendorName: 'كوشة وفرح لتنسيق الحفلات',
        vendorId: 'vendor-2',
        pricePortion: 12000,
        included: true,
        customizable: true
      },
      {
        categoryName: 'عروض وفنون',
        serviceName: 'فرقة العرضة النجدية والسامري 12 مؤدي لاستقبال الرجال',
        vendorName: 'فرقة سيوف نجد',
        vendorId: 'vendor-6',
        pricePortion: 4500,
        included: true,
        customizable: true
      },
      {
        categoryName: 'تصوير وتوثيق',
        serviceName: 'فريق تصوير نسائي ورجالي سينمائي + درون + ألبومات حرارية',
        vendorName: 'استوديو وميض',
        vendorId: 'vendor-3',
        pricePortion: 6500,
        included: true,
        customizable: true
      },
      {
        categoryName: 'ضيافة وبوفيه',
        serviceName: 'ضيافة القهوة السعودية + 4 صبابين للرجال و 4 مباشرات للنساء',
        vendorName: 'ضيافة نجد الأصيلة',
        vendorId: 'vendor-1',
        pricePortion: 5000,
        included: true,
        customizable: true
      },
      {
        categoryName: 'توزيعات وبخور',
        serviceName: 'طاولات تبخير مستمر بدهن العود + 200 توزيعة هدايا فاخرة',
        vendorName: 'دار البخور والعود الملكي',
        vendorId: 'vendor-7',
        pricePortion: 5500,
        included: true,
        customizable: true
      },
      {
        categoryName: 'إدارة المدعوين والـ QR',
        serviceName: 'نظام إدارة طاولات ودعوات VIP ومسح QR عند البوابات',
        vendorName: 'منصة مناسبتي الرقمية',
        vendorId: 'vendor-internal',
        pricePortion: 1000,
        included: true,
        customizable: false
      }
    ]
  }
];

export const INITIAL_OCCASIONS: Occasion[] = [
  {
    id: 'occ-101',
    title: 'حفل تخرج دكتورة سارة من كلية الطب',
    occasionTypeId: 'graduation',
    occasionTypeNameAr: 'تخرج',
    cityId: 'riyadh',
    cityNameAr: 'الرياض',
    neighborhood: 'حطين',
    date: '2026-10-25',
    time: '08:00 م',
    isApproximateDate: false,
    guestCount: 80,
    guestsSection: 'women',
    venueType: 'chalet',
    venueName: 'شاليهات الأوركيد الفاخرة - حطين',
    budget: 25000,
    spent: 18400,
    tier: 'luxury',
    readinessPercentage: 74,
    status: 'planning',
    createdAt: '2026-09-01T14:30:00Z',
    notes: 'حفلة تخرج نسائية مع التركيز على طابع الورد الطبيعي والأبيض والذهبي والتصوير الفوتوغرافي.',
    coPlanners: [
      { name: 'أم سارة', role: 'coplanner', phone: '+966501112233' },
      { name: 'نورة (أخت الخريجة)', role: 'coplanner', phone: '+966504445566' }
    ]
  },
  {
    id: 'occ-102',
    title: 'عقد قران وملكة فيصل ونوف',
    occasionTypeId: 'melka',
    occasionTypeNameAr: 'ملكة / عقد قران',
    cityId: 'jeddah',
    cityNameAr: 'جدة',
    neighborhood: 'الشاطئ',
    date: '2026-11-15',
    time: '08:30 م',
    isApproximateDate: false,
    guestCount: 120,
    guestsSection: 'families',
    venueType: 'hall',
    venueName: 'قاعة الياقوت - فندق روزوود جدة',
    budget: 60000,
    spent: 42000,
    tier: 'luxury',
    readinessPercentage: 85,
    status: 'confirmed',
    createdAt: '2026-08-20T10:00:00Z',
    notes: 'ملكة عائلية راقية مع طاولة عقد قران مخصصة وإطلالة على البحر.',
  }
];

export const INITIAL_GUESTS: Guest[] = [
  {
    id: 'gst-1',
    occasionId: 'occ-101',
    name: 'الدكتورة أمل العتيبي',
    phone: '+966501239988',
    category: 'women',
    familyGroup: 'صديقات الجامعة',
    companionCount: 1,
    status: 'confirmed',
    qrCode: 'MUN-GST-101-01',
    tableId: 'tbl-1',
    tableName: 'طاولة الخريجات VIP',
    invitedVia: 'whatsapp',
    invitationSentAt: '2026-09-10T12:00:00Z',
    rsvpTime: '2026-09-10T15:30:00Z',
  },
  {
    id: 'gst-2',
    occasionId: 'occ-101',
    name: 'منى السليمان',
    phone: '+966554433221',
    category: 'women',
    familyGroup: 'العائلة المقربة',
    companionCount: 2,
    status: 'confirmed',
    qrCode: 'MUN-GST-101-02',
    tableId: 'tbl-2',
    tableName: 'طاولة العائلة (أهل العروس)',
    invitedVia: 'whatsapp',
    invitationSentAt: '2026-09-10T12:00:00Z',
    rsvpTime: '2026-09-10T18:20:00Z',
  },
  {
    id: 'gst-3',
    occasionId: 'occ-101',
    name: 'هدى القحطاني',
    phone: '+966567711223',
    category: 'women',
    familyGroup: 'صديقات الجامعة',
    companionCount: 0,
    status: 'attended',
    qrCode: 'MUN-GST-101-03',
    tableId: 'tbl-1',
    tableName: 'طاولة الخريجات VIP',
    invitedVia: 'whatsapp',
    invitationSentAt: '2026-09-10T12:00:00Z',
    rsvpTime: '2026-09-11T09:00:00Z',
  },
  {
    id: 'gst-4',
    occasionId: 'occ-101',
    name: 'ريما الشمري',
    phone: '+966548899001',
    category: 'women',
    familyGroup: 'العائلة',
    companionCount: 1,
    status: 'invited',
    qrCode: 'MUN-GST-101-04',
    invitedVia: 'whatsapp',
    invitationSentAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'gst-5',
    occasionId: 'occ-101',
    name: 'نورة الدوسري',
    phone: '+966532211445',
    category: 'women',
    familyGroup: 'الجيران',
    companionCount: 0,
    status: 'declined',
    qrCode: 'MUN-GST-101-05',
    invitedVia: 'whatsapp',
    invitationSentAt: '2026-09-10T12:00:00Z',
    notes: 'اعتذرت لوجود سفر خارج المملكة',
  }
];

export const INITIAL_TABLES: SeatingTable[] = [
  {
    id: 'tbl-1',
    occasionId: 'occ-101',
    name: 'طاولة الخريجات VIP (طاولة 1)',
    capacity: 10,
    section: 'women',
    assignedGuestIds: ['gst-1', 'gst-3'],
  },
  {
    id: 'tbl-2',
    occasionId: 'occ-101',
    name: 'طاولة العائلة الكريمة (طاولة 2)',
    capacity: 12,
    section: 'women',
    assignedGuestIds: ['gst-2'],
  },
  {
    id: 'tbl-3',
    occasionId: 'occ-101',
    name: 'طاولة الزميلات والصديقات (طاولة 3)',
    capacity: 10,
    section: 'women',
    assignedGuestIds: [],
  }
];

export const INITIAL_BUDGET_ITEMS: BudgetItem[] = [
  {
    id: 'bgt-1',
    occasionId: 'occ-101',
    categoryId: 'decor',
    categoryNameAr: 'كوشة وديكور القاعة',
    allocatedAmount: 6000,
    spentAmount: 5500,
    status: 'booked',
    vendorId: 'vendor-2',
    vendorName: 'كوشة وفرح لتنسيق الحفلات',
  },
  {
    id: 'bgt-2',
    occasionId: 'occ-101',
    categoryId: 'photography',
    categoryNameAr: 'تصوير فوتوغراف وفيديو سينمائي',
    allocatedAmount: 4000,
    spentAmount: 3800,
    status: 'booked',
    vendorId: 'vendor-3',
    vendorName: 'استوديو وميض',
  },
  {
    id: 'bgt-3',
    occasionId: 'occ-101',
    categoryId: 'hospitality',
    categoryNameAr: 'بوفيه وضيافة القهوة السعودية والمباشرات',
    allocatedAmount: 7000,
    spentAmount: 6200,
    status: 'booked',
    vendorId: 'vendor-1',
    vendorName: 'ضيافة نجد الأصيلة',
  },
  {
    id: 'bgt-4',
    occasionId: 'occ-101',
    categoryId: 'cake',
    categoryNameAr: 'كيكة التخرج وحلا التقديم',
    allocatedAmount: 2000,
    spentAmount: 1400,
    status: 'paid',
    vendorId: 'vendor-5',
    vendorName: 'حلويات لافندر سويتس',
  },
  {
    id: 'bgt-5',
    occasionId: 'occ-101',
    categoryId: 'giveaways',
    categoryNameAr: 'توزيعات المعازيم والمباخر بالاسم',
    allocatedAmount: 3000,
    spentAmount: 1500,
    status: 'estimated',
    vendorId: 'vendor-7',
    vendorName: 'دار البخور والعود الملكي',
  },
  {
    id: 'bgt-6',
    occasionId: 'occ-101',
    categoryId: 'invitations',
    categoryNameAr: 'الدعوات الرقمية ونظام الـ QR',
    allocatedAmount: 1000,
    spentAmount: 0,
    status: 'estimated',
  }
];

export const INITIAL_TASKS: PlanningTask[] = [
  {
    id: 'tsk-1',
    occasionId: 'occ-101',
    title: 'تأكيد حجز الشاليه ودفع العربون',
    category: 'الموقع',
    dueDaysBefore: 30,
    dueDate: '2026-09-25',
    isCompleted: true,
    priority: 'high',
  },
  {
    id: 'tsk-2',
    occasionId: 'occ-101',
    title: 'اعتماد تصميم كوشة التخرج وكتابة اسم الدكتورة سارة',
    category: 'الديكور',
    dueDaysBefore: 20,
    dueDate: '2026-10-05',
    isCompleted: true,
    priority: 'high',
  },
  {
    id: 'tsk-3',
    occasionId: 'occ-101',
    title: 'إرسال بطاقات الدعوة الرقمية لجميع المدعوات وتتبع الـ RSVP',
    category: 'الدعوات',
    dueDaysBefore: 14,
    dueDate: '2026-10-11',
    isCompleted: true,
    priority: 'high',
  },
  {
    id: 'tsk-4',
    occasionId: 'occ-101',
    title: 'تحديد قائمة نكهات الكيك واختيار عبارات التهنئة',
    category: 'الضيافة',
    dueDaysBefore: 10,
    dueDate: '2026-10-15',
    isCompleted: false,
    priority: 'medium',
  },
  {
    id: 'tsk-5',
    occasionId: 'occ-101',
    title: 'استلام بوكسات توزيعات العود والمباخر والتأكد من الأسماء',
    category: 'الهدايا',
    dueDaysBefore: 5,
    dueDate: '2026-10-20',
    isCompleted: false,
    priority: 'medium',
  },
  {
    id: 'tsk-6',
    occasionId: 'occ-101',
    title: 'التنسيق النهائي مع المصورة على موعد الوصول وجلسة التصوير الخاصة',
    category: 'التصوير',
    dueDaysBefore: 2,
    dueDate: '2026-10-23',
    isCompleted: false,
    priority: 'high',
  }
];

export const INITIAL_WISHLIST: WishlistGift[] = [
  {
    id: 'wsh-1',
    occasionId: 'occ-101',
    title: 'عربة آيسكريم ومشروبات منعشة للحفل (إهداء مناسبة)',
    price: 1200,
    category: 'ضيافة',
    imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80',
    isFulfilled: true,
    giftedBy: 'خالتي حصة العتيبي',
    allowContributions: false,
    contributedAmount: 1200,
    isServiceGift: true,
    serviceVendorName: 'ضيافة نجد الأصيلة',
  },
  {
    id: 'wsh-2',
    occasionId: 'occ-101',
    title: 'طقم مجوهرات وساعة تخرج ذهبية فخمة',
    price: 4500,
    category: 'هدايا شخصية',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    isFulfilled: false,
    allowContributions: true,
    contributedAmount: 3000,
    isServiceGift: false,
  },
  {
    id: 'wsh-3',
    occasionId: 'occ-101',
    title: 'ترقية باقة التصوير لإضافة ألبوم إيطالي مذهب وفيديو درون',
    price: 1500,
    category: 'تصوير',
    imageUrl: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=600&auto=format&fit=crop&q=80',
    isFulfilled: false,
    allowContributions: true,
    contributedAmount: 500,
    isServiceGift: true,
    serviceVendorName: 'استوديو وميض',
  }
];

export const INSPIRATION_POSTS: InspirationPost[] = [
  {
    id: 'insp-1',
    titleAr: 'تنسيق حفل تخرج استثنائي بطابع الورود البيضاء واللوحات الأكريليك',
    occasionTypeId: 'graduation',
    occasionTypeNameAr: 'تخرج',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=800&auto=format&fit=crop&q=80',
    likesCount: 1420,
    savesCount: 612,
    tags: ['تخرج_2026', 'كوشة_تخرج', 'الرياض', 'ورد_طبيعي'],
    descriptionAr: 'تصميم مودرن لخلفية تخرج أكريليك مع إضاءة دافئة وتنسيق زهور هولندية فخمة بحي الملقا بالرياض.',
    cityNameAr: 'الرياض',
    taggedVendors: [
      { vendorId: 'vendor-2', vendorName: 'كوشة وفرح لتنسيق الحفلات', category: 'كوش وديكور', servicePrice: 3800 },
      { vendorId: 'vendor-5', vendorName: 'حلويات لافندر سويتس', category: 'كيك وحلويات', servicePrice: 1400 },
      { vendorId: 'vendor-3', vendorName: 'استوديو وميض', category: 'تصوير', servicePrice: 2400 }
    ]
  },
  {
    id: 'insp-2',
    titleAr: 'عقد قران ملكي بديكور القصر وإطلالة بحرية ساحرة بجدة',
    occasionTypeId: 'melka',
    occasionTypeNameAr: 'ملكة / عقد قران',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80',
    likesCount: 2310,
    savesCount: 940,
    tags: ['ملكة', 'عقد_قران', 'عروس_جدة', 'طاولة_الشبكة'],
    descriptionAr: 'تفاصيل عقد قران رومانسي مع طاولة شبكة رخامية وتوزيعات عود موروكي مذهب.',
    cityNameAr: 'جدة',
    taggedVendors: [
      { vendorId: 'vendor-2', vendorName: 'كوشة وفرح لتنسيق الحفلات', category: 'كوش وديكور', servicePrice: 4500 },
      { vendorId: 'vendor-7', vendorName: 'دار البخور والعود الملكي', category: 'توزيعات', servicePrice: 1750 }
    ]
  },
  {
    id: 'insp-3',
    titleAr: 'أجواء العرضة السعودية النجدية في زفاف فاخر بالدرعية',
    occasionTypeId: 'wedding',
    occasionTypeNameAr: 'زواج',
    mediaType: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=800&auto=format&fit=crop&q=80',
    likesCount: 3105,
    savesCount: 1208,
    tags: ['عرضة_سعودية', 'زواج_الرياض', 'أعراس_الدرعية', 'كرم_الضيافة'],
    descriptionAr: 'استقبال ضيوف العرس بالعرضة النجدية الرسمية والسيوف المذهبة ودلال الرسلان.',
    cityNameAr: 'الرياض',
    taggedVendors: [
      { vendorId: 'vendor-6', vendorName: 'فرقة سيوف نجد', category: 'فنون وترفيه', servicePrice: 4500 },
      { vendorId: 'vendor-1', vendorName: 'ضيافة نجد الأصيلة', category: 'ضيافة', servicePrice: 2500 }
    ]
  }
];

export const INITIAL_RFQS: RFQRequest[] = [
  {
    id: 'rfq-201',
    occasionId: 'occ-101',
    occasionTitle: 'حفل تخرج دكتورة سارة من كلية الطب',
    occasionTypeAr: 'تخرج',
    cityAr: 'الرياض',
    date: '2026-10-25',
    guestCount: 80,
    budget: 6000,
    requirementsAr: 'مطلوب كوشة تخرج 4 أمتار مع ورد طبيعي وبورد ترحيبي مضيء بالاسم، مع إضاءات مسرح وطاولة تقديم الكيك والتوزيعات.',
    quotesCount: 3,
    status: 'open',
    createdAt: '2026-09-05T11:00:00Z',
    quotes: [
      {
        id: 'quo-1',
        vendorId: 'vendor-2',
        vendorName: 'كوشة وفرح لتنسيق الحفلات',
        vendorLogo: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=300&auto=format&fit=crop&q=80',
        rating: 4.88,
        basePrice: 4200,
        setupFee: 300,
        transportFee: 200,
        vat: 705,
        total: 5405,
        optionalItems: [
          { title: 'إضافة ستاند بالونات هيليوم فاخر', price: 600 },
          { title: 'شاشة بروجكتر لعرض فيديو التخرج', price: 800 }
        ],
        deliveryTimeAr: 'التركيب قبل الحفل بـ 4 ساعات والتسليم المسبق',
        notesAr: 'العرض يشمل كتابة اسم الدكتورة سارة بالأكريليك المضيء الذهبي مع ورود هولندية طبيعية ونضمن جودة التنفيذ 100%.',
        status: 'pending',
        isBestValue: true,
        isClosestBudget: true,
      },
      {
        id: 'quo-2',
        vendorId: 'vendor-alt-1',
        vendorName: 'مؤسسة زهرة الأوركيد للديكور',
        vendorLogo: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=300&auto=format&fit=crop&q=80',
        rating: 4.72,
        basePrice: 4800,
        setupFee: 400,
        transportFee: 250,
        vat: 817.5,
        total: 6267.5,
        optionalItems: [
          { title: 'تزيين طاولة طعام المعازيم بالورود', price: 1200 }
        ],
        deliveryTimeAr: 'التركيب في نفس يوم المناسبة ظهراً',
        notesAr: 'ورد مستورد وتنسيق راقي مع ضمان استبدال أي وردة تالفة.',
        status: 'pending',
        isHighestRated: false,
      },
      {
        id: 'quo-3',
        vendorId: 'vendor-alt-2',
        vendorName: 'تصاميم إشراقة للمناسبات',
        vendorLogo: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=300&auto=format&fit=crop&q=80',
        rating: 4.95,
        basePrice: 5200,
        setupFee: 0,
        transportFee: 0,
        vat: 780,
        total: 5980,
        optionalItems: [
          { title: 'إضاءة متحركة احترافية (Moving Heads)', price: 900 }
        ],
        deliveryTimeAr: 'جاهزية كاملة قبل 5 ساعات من الحفل',
        notesAr: 'سعر شامل النقل والتركيب والإزالة، مع وجود مشرفة موقع طوال فترة الحفل.',
        status: 'pending',
        isFastest: true,
        isHighestRated: true,
      }
    ]
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bok-501',
    bookingNumber: 'MUN-2026-9812',
    occasionId: 'occ-101',
    occasionTitle: 'حفل تخرج دكتورة سارة من كلية الطب',
    vendorId: 'vendor-1',
    vendorName: 'ضيافة نجد الأصيلة',
    vendorLogo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
    serviceTitleAr: 'خدمة ضيافة القهوة السعودية الملكية والتمور (80 شخص)',
    date: '2026-10-25',
    time: '08:00 م',
    cityAr: 'الرياض',
    customerName: 'سارة العتيبي',
    customerPhone: '+966501234567',
    totalAmount: 1897.5,
    depositAmount: 500,
    remainingAmount: 1397.5,
    depositPaid: true,
    isFullyPaid: false,
    paymentMethod: 'mada',
    status: 'confirmed',
    cancellationPolicyAr: 'إلغاء مجاني حتى 5 أيام قبل الحفل.',
    createdAt: '2026-09-02T16:00:00Z',
    deliverablesAr: [
      'حضور 2 مباشرات بزي سعودي تراثي موحد',
      'توفير دلال رسلان نحاسية وشاي كرك ونعناع',
      'توفير 4 كجم سكري مفتل محشي ومكسرات',
      'تبخير القاعة بدهن العود الطبيعي'
    ]
  },
  {
    id: 'bok-502',
    bookingNumber: 'MUN-2026-9813',
    occasionId: 'occ-101',
    occasionTitle: 'حفل تخرج دكتورة سارة من كلية الطب',
    vendorId: 'vendor-3',
    vendorName: 'استوديو وميض',
    vendorLogo: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=300&auto=format&fit=crop&q=80',
    serviceTitleAr: 'باقة تصوير المناسبات والتخرج VIP',
    date: '2026-10-25',
    time: '07:30 م',
    cityAr: 'الرياض',
    customerName: 'سارة العتيبي',
    customerPhone: '+966501234567',
    totalAmount: 2760,
    depositAmount: 800,
    remainingAmount: 1960,
    depositPaid: true,
    isFullyPaid: false,
    paymentMethod: 'apple_pay',
    status: 'confirmed',
    cancellationPolicyAr: 'إلغاء متاح حتى 10 أيام قبل الموعد.',
    createdAt: '2026-09-03T11:20:00Z',
    deliverablesAr: [
      'مصورة فوتوغراف ومصورة فيديو محترفتين',
      'تغطية 4 ساعات وتسليم ألبوم حراري فاخر',
      'فيديو ريلز سينمائي مدة دقيقة'
    ]
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    vendorId: 'vendor-1',
    vendorName: 'ضيافة نجد الأصيلة',
    bookingId: 'bok-demo-1',
    customerName: 'أم فهد القحطاني',
    customerCityAr: 'الرياض',
    occasionTypeAr: 'زواج',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-08-18',
    commentAr: 'ما شاء الله تبارك الله، بيّضوا وجوهنا قدام المعازيم! القهوة تصب حارة والتمور فاخرة والمباشرات قمة في الذوق واللباقة. أنصح بالتعامل معهم وبقوة.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    vendorReplyAr: 'شهادة نعتز بها يا أم فهد، ونسعد دائماً بخدمتكم في أفراحكم ومناسباتكم السعيدة.'
  },
  {
    id: 'rev-2',
    vendorId: 'vendor-2',
    vendorName: 'كوشة وفرح لتنسيق الحفلات',
    bookingId: 'bok-demo-2',
    customerName: 'نوف الشمري',
    customerCityAr: 'الرياض',
    occasionTypeAr: 'ملكة',
    rating: 4.9,
    qualityRating: 5.0,
    punctualityRating: 4.8,
    communicationRating: 5.0,
    valueRating: 4.8,
    date: '2026-08-25',
    commentAr: 'الكوشة طلعت على الواقع أجمل بكثير من الصور! دقة في الألوان والورد طبيعي وريحته تفتح النفس. الالتزام بالوقت كان ممتاز وخلصوا التركيب قبل الموعد بساعتين.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-3',
    vendorId: 'vendor-3',
    vendorName: 'استوديو وميض',
    bookingId: 'bok-demo-3',
    customerName: 'دلال الدوسري',
    customerCityAr: 'الرياض',
    occasionTypeAr: 'تخرج',
    rating: 4.95,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 4.9,
    valueRating: 4.9,
    date: '2026-09-02',
    commentAr: 'المصورة كانت مريحة جداً وأفكارها في اللقطات إبداعية وسينمائية. استلمت الألبوم والريلز بجودة خيالية وما أخذوا أسبوع في التسليم.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-4',
    vendorId: 'vendor-4',
    vendorName: 'قصر الفيروز للاحتفالات والمؤتمرات',
    bookingId: 'bok-demo-4',
    customerName: 'د. عبدالملك التميمي',
    customerCityAr: 'الرياض',
    occasionTypeAr: 'حفل زفاف',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-09-05',
    commentAr: 'تنظيم قصر الفيروز استثنائي! القاعات واسعة ونظام التكييف والصوتيات ممتاز، ومواقف السيارات كانت ميسرة لكافة الضيوف. منصة مناسبتي سهلت الدفع وعقد الزكاة والضريبة ZATCA بضغطة زر.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    vendorReplyAr: 'بارك الله لكما وبارك عليكما وجمع بينكما في خير يا دكتور، شرفنا خدمتكم.'
  },
  {
    id: 'rev-5',
    vendorId: 'vendor-9',
    vendorName: 'قصر ليلتي للاحتفالات الملكية',
    bookingId: 'bok-demo-5',
    customerName: 'نورة العتيبي',
    customerCityAr: 'جدة',
    occasionTypeAr: 'عرس ملكي',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-09-08',
    commentAr: 'قصر ليلتي في جدة فخامة لا توصف.. الإطلالة البحرية وديكور الثريات كان ساحر لكل الحضور. كل تفصيلة تم ترتيبها عبر منصة مناسبتي بأعلى درجات الاحترافية.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-6',
    vendorId: 'vendor-11',
    vendorName: 'فلورا آرت لتنسيق الكوش والزهور الفاخرة',
    bookingId: 'bok-demo-6',
    customerName: 'فيصل الدوسري',
    customerCityAr: 'الخبر',
    occasionTypeAr: 'عقد قران وملكة',
    rating: 4.94,
    qualityRating: 5.0,
    punctualityRating: 4.9,
    communicationRating: 4.9,
    valueRating: 4.9,
    date: '2026-09-10',
    commentAr: 'تعاملت مع فلورا آرت بالخبر لتنسيق حفلة ملكتي، الورود الهولندية كانت منتعشة وتنسيق الألوان متناسق جداً مع الثيم. المنسق كان متجاوب طوال الوقت.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-7',
    vendorId: 'vendor-6',
    vendorName: 'فرقة سيوف نجد للعرضة والفنون التراثية',
    bookingId: 'bok-demo-7',
    customerName: 'م. خالد الشمري',
    customerCityAr: 'الرياض',
    occasionTypeAr: 'احتفال يوم التأسيس',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-08-30',
    commentAr: 'حجزنا فرقة سيوف نجد لاحتفال شركتنا باليوم الوطني والتأسيس.. أداء العرضة النجدية هز القاعة بالحماس والشيلات كانت قمة الفخر والأصالة. الكل أثنى عليهم.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-8',
    vendorId: 'vendor-16',
    vendorName: 'ريماس للشوكولاتة البلجيكية وكيك المناسبات',
    bookingId: 'bok-demo-8',
    customerName: 'د. ريم المطيري',
    customerCityAr: 'المدينة المنورة',
    occasionTypeAr: 'استقبال مولود',
    rating: 4.92,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 4.8,
    valueRating: 4.9,
    date: '2026-09-04',
    commentAr: 'شوكولاتة بلجيكية فاخرة وطباعة اسم المولود كانت دقيقة وأنيقة جداً. صواني التقديم وصلت باردة وجاهزة، والضيوف كلهم سألوني من وين طلبتها.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-9',
    vendorId: 'vendor-12',
    vendorName: 'فرقة أنغام الحجاز للمجرور والمزمار والعرضة',
    bookingId: 'bok-demo-9',
    customerName: 'راكان الحربي',
    customerCityAr: 'مكة المكرمة',
    occasionTypeAr: 'ملكة',
    rating: 4.95,
    qualityRating: 5.0,
    punctualityRating: 4.9,
    communicationRating: 5.0,
    valueRating: 4.9,
    date: '2026-09-01',
    commentAr: 'أحيوا ليلة ملكتي في مكة بأروع مجرور ومزمار حجازي، الطاقم لبسهم تراثي كامل ومنظمين في الدخول والأهازيج. بيض الله وجوهكم.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-10',
    vendorId: 'vendor-14',
    vendorName: 'استوديو أضواء الجنوب للتصوير السينمائي',
    bookingId: 'bok-demo-10',
    customerName: 'مها الغامدي',
    customerCityAr: 'أبها',
    occasionTypeAr: 'زواج',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-08-28',
    commentAr: 'التصوير السينمائي بين غيوم السودة وطبيعة أبها طلع شي خيالي! المصورة كانت صبورة وذوق، وسلمونا الألبوم الحراري وفيديوهات الريلز قبل الموعد.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-11',
    vendorId: 'vendor-10',
    vendorName: 'مطابخ الريف الحجازي للبوفيهات والذبائح',
    bookingId: 'bok-demo-11',
    customerName: 'تركي البقمي',
    customerCityAr: 'الطائف',
    occasionTypeAr: 'عزيمة عائلية',
    rating: 4.9,
    qualityRating: 5.0,
    punctualityRating: 4.8,
    communicationRating: 5.0,
    valueRating: 4.8,
    date: '2026-08-22',
    commentAr: 'السليق الطائفي والمفاطيح كانت حارة وطازجة ولذيذة جداً، خدمة المباشرين والترتيب واجهت قدام كبار الضيوف.',
    isVerifiedBooking: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-12',
    vendorId: 'vendor-13',
    vendorName: 'تمور ومباخر هجر الفاخرة',
    bookingId: 'bok-demo-12',
    customerName: 'عبدالمحسن الأحسائي',
    customerCityAr: 'الأحساء',
    occasionTypeAr: 'عقد قران',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-08-15',
    commentAr: 'مباخر العود الخشبية وتوزيعات الخلاص الأحسائي المحشو بالهيل كانت فكرة مميزة أثنى عليها جميع الضيوف، شكراً على الجودة والسرعة.',
    isVerifiedBooking: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-13',
    vendorId: 'vendor-7',
    vendorName: 'دار البخور والعود الملكي',
    bookingId: 'bok-demo-13',
    customerName: 'فهد الرويلي',
    customerCityAr: 'تبوك',
    occasionTypeAr: 'حفل تخرج',
    rating: 4.88,
    qualityRating: 4.9,
    punctualityRating: 5.0,
    communicationRating: 4.8,
    valueRating: 4.8,
    date: '2026-09-06',
    commentAr: 'توزيعات العود الموروكي وصلت تبوك بتغليف فخم ومحكم بدون أي تلف، ورائحة العود ثباتها عالي ومميز.',
    isVerifiedBooking: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-14',
    vendorId: 'vendor-15',
    vendorName: 'منتجع ومخيمات واحة العلا للمناسبات الخاصة',
    bookingId: 'bok-demo-14',
    customerName: 'سلطان العنزي',
    customerCityAr: 'العلا',
    occasionTypeAr: 'مناسبة خاصة',
    rating: 5.0,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 5.0,
    date: '2026-09-09',
    commentAr: 'أمسية لا تنسى بين جبال العلا الساحرة.. الإضاءات والخيام الملكية والخدمة الفندقية كانت فوق التوقعات. تجربة استثنائية بكل المقاييس.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-15',
    vendorId: 'vendor-18',
    vendorName: 'فرقة صدى الجنوب للخطوة والعرضة الجنوبية',
    bookingId: 'bok-demo-15',
    customerName: 'حصة العسيري',
    customerCityAr: 'أبها',
    occasionTypeAr: 'زواج',
    rating: 4.98,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 5.0,
    valueRating: 4.9,
    date: '2026-09-07',
    commentAr: 'أداء الخطوة العسيرية والشيلات الجنوبية كان حماسي جداً ورفع رأسنا قدام المعازيم، التزام بالوقت ولباس جنوبي أصيل بالخناجر.',
    isVerifiedBooking: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'rev-16',
    vendorId: 'vendor-17',
    vendorName: 'دلة الفخامة لصبابين القهوة والمباشرين',
    bookingId: 'bok-demo-16',
    customerName: 'وسمية الدخيل',
    customerCityAr: 'الدمام',
    occasionTypeAr: 'ملكة',
    rating: 4.95,
    qualityRating: 5.0,
    punctualityRating: 5.0,
    communicationRating: 4.9,
    valueRating: 4.9,
    date: '2026-09-03',
    commentAr: 'صبابين ومباشرات دلة الفخامة في الدمام قمة في الذوق واللباقة، الدلال النحاسية تصب قهوة شقراء خنينة والبخور معطر الصالة طول الحفل.',
    isVerifiedBooking: true,
    featured: true,
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_ADMIN_CONFIG: AdminPlatformConfig = {
  platformNameAr: 'مناسبتـي',
  platformNameEn: 'Munasabati',
  taglineAr: 'خططها. احجزها. اعزمهم. احتفل.',
  commissionRatePercent: 10,
  vatPercent: 15,
  currencyAr: 'ر.س',
  emergencyPhone: '920012345',
  aiAssistantNameAr: 'لُـمى',
  activeCitiesCount: 12,
  totalGMV: 6420000,
  totalBookings: 4180,
  totalUsers: 24500,
  totalVendors: 530,
  announcementText: '✨ مرحباً بكم في منصة مناسبتـي — احجز أفضل قاعات وموردي المناسبات بالمملكة مع توثيق رسمي وضمان دفع آمن 100% 🇸🇦',
  isMaintenanceMode: false,
  defaultEscrowDays: 3,
  autoApproveReviews: true,
};

export const INITIAL_RUN_OF_SHOW_ITEMS: RunOfShowItem[] = [
  {
    id: 'ros-1',
    occasionId: 'occ-demo-1',
    time: '16:00',
    titleAr: 'وصول فريق التنسيق والكوشة والإضاءة',
    descriptionAr: 'استلام القاعة من إدارة الفندق ومطابقة الإعدادات والزهور ومسرح الكوشة ومكبرات الصوت.',
    responsibleRole: 'coordinator',
    responsibleRoleAr: 'منسق الحفل',
    responsiblePerson: 'م. فهد السبيعي',
    responsiblePhone: '+966501112233',
    status: 'completed',
    durationMinutes: 120,
    iconName: 'Sparkles',
    notes: 'التأكد من تشغيل التكييف قبل وصول الضيوف بساعتين.'
  },
  {
    id: 'ros-2',
    occasionId: 'occ-demo-1',
    time: '18:30',
    titleAr: 'وصول فريق التصوير الفوتوغرافي والفيديو',
    descriptionAr: 'تجهيز الكاميرات والدرون، تصوير تفاصيل القاعة والديكورات قبل دخول الضيوف وتصوير لقطات البورتريه الأولى.',
    responsibleRole: 'photographer',
    responsibleRoleAr: 'فريق التصوير',
    responsiblePerson: 'استوديو وميض',
    responsiblePhone: '+966555554433',
    status: 'completed',
    durationMinutes: 45,
    iconName: 'Camera',
    notes: 'التركيز على تفاصيل كروت الطاولات وتوزيعات الضيوف.'
  },
  {
    id: 'ros-3',
    occasionId: 'occ-demo-1',
    time: '19:30',
    titleAr: 'بدء استقبال الضيوف والترحيب مع الضيافة الأولى',
    descriptionAr: 'افتتاح بوابات الاستقبال، تقديم القهوة السعودية المعتدلة مع تمر السكري والتمريات الفاخرة والعصائر الطازجة.',
    responsibleRole: 'catering',
    responsibleRoleAr: 'فريق الضيافة والصبابين',
    responsiblePerson: 'قهوة وهيل للضيافة',
    responsiblePhone: '+966500001122',
    status: 'in_progress',
    durationMinutes: 90,
    iconName: 'Coffee',
    notes: 'الاستعداد التام عند البوابات ووجود مشرفين لمسح كروت QR.'
  },
  {
    id: 'ros-4',
    occasionId: 'occ-demo-1',
    time: '21:00',
    titleAr: 'مسيرة دخول العريس والعرضة النجدية',
    descriptionAr: 'بدء فرقة العرضة النجدية، اصطفاف الأقارب والترحيب بالمعازيم ومسيرة العريس مع الأهازيج التراثية.',
    responsibleRole: 'music',
    responsibleRoleAr: 'فرقة العرضة',
    responsiblePerson: 'فرقة الرياض للفنون',
    responsiblePhone: '+966504443322',
    status: 'pending',
    durationMinutes: 45,
    iconName: 'Music',
    notes: 'التنسيق مع مهندس الصوت لتجهيز الشيلات الحماسية.'
  },
  {
    id: 'ros-5',
    occasionId: 'occ-demo-1',
    time: '22:15',
    titleAr: 'تقديم بوفيه العشاء الفاخر والذبائح النجدية',
    descriptionAr: 'فتح صالة الطعام، تقديم المفاطيح النجدية والبوفيه المفتوح والمقبلات الساخنة والباردة.',
    responsibleRole: 'catering',
    responsibleRoleAr: 'متعهد الإعاشة',
    responsiblePerson: 'مطابخ قصر الضيافة',
    responsiblePhone: '+966508889900',
    status: 'pending',
    durationMinutes: 75,
    iconName: 'Utensils',
    notes: 'التأكد من سخونة الأطباق وتواجد طاقم الخدمة على الطاولات.'
  },
  {
    id: 'ros-6',
    occasionId: 'occ-demo-1',
    time: '23:45',
    titleAr: 'تقطيع الكيكة وتوزيعات مسك الختام والعود',
    descriptionAr: 'مراسم تقطيع كيكة الزفاف وتمرير المباخر ودهن العود الملكي على الضيوف وتوديعهم.',
    responsibleRole: 'family',
    responsibleRoleAr: 'أهل المناسبة والمنسق',
    responsiblePerson: 'أم العريس ومساعد التنسيق',
    responsiblePhone: '+966501112233',
    status: 'pending',
    durationMinutes: 45,
    iconName: 'Gift',
    notes: 'تجهيز المباخر الفاخرة وتوزيع الهدايا التذكارية.'
  }
];

